name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - .github/workflows/release.yml
      - '**.png'
      - '**.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cache
      uses: coursier/cache-action@v6
    - name: coursier-setup
      uses: laughedelic/coursier-setup@v1
      with:
        jvm: graalvm-java11:21.0.0
    - name: test
      run: sbtn test
