name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - .github/workflows/release-new.yml
      - '**.png'
      - '**.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cache
      uses: coursier/cache-action@v6
    - name: coursier-setup
      uses: laughedelic/coursier-setup@v1
      with:
        jvm: graalvm-community:24.0.2
    - name: test
      run: sbtn test
