name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cache
      uses: coursier/cache-action@v5      
    - name: coursier-setup
      uses: laughedelic/coursier-setup@v1
      with:
        jvm: adopt:11
        apps: sbtn
    - name: build
      run: |
        sbtn publishLocal
        cs bootstrap -o bson-json-to-csv --standalone tech.bilal:jsontocsv_3.0.0-RC1:0.1.0-SNAPSHOT -f -r jitpack
        chmod +x bson-json-to-csv
    - name: publish          
      uses: softprops/action-gh-release@v1
      with:
        files: bson-json-to-csv
        body_path: changelog/${{ github.event.release.tag_name }}.md
        tag_name: ${{ github.event.release.tag_name }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

