name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cache
      uses: coursier/cache-action@v6
    - name: coursier-setup
      uses: laughedelic/coursier-setup@v1
      with:
        jvm: graalvm-java11:21.0.0
    - name: build
      run: sbt nativeImage
    - name: publish
      uses: softprops/action-gh-release@v1
      with:
        files: bson-json-to-csv
        body_path: changelog/${{ github.event.release.tag_name }}.md
        tag_name: ${{ github.event.release.tag_name }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

